import { Product } from "../../shared/types";

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "iPhone 15 Pro Max",
    title: "iPhone 15 Pro Max",
    description:
      "The latest iPhone with advanced camera system and powerful A17 Pro chip",
    specifications: {
      Display: "6.7-inch Super Retina XDR",
      Chip: "A17 Pro",
      Camera: "48MP Main, 12MP Ultra Wide, 12MP Telephoto",
      Storage: "256GB",
    },
    category: "electronics",
    old_price: 149900,
    our_price: 134900,
    mrp: 149900,
    discount_percentage: 10,
    discount: 10,
    images: [
      "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=500&h=500&fit=crop",
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=500&h=500&fit=crop",
    ],
    in_stock: true,
    average_rating: 4.8,
    rating: 4.8,
    review_count: 245,
    reviews: [],
    features: [
      "5G Connectivity",
      "Face ID",
      "Wireless Charging",
      "Water Resistant",
    ],
    tags: ["smartphone", "apple", "premium"],
    sizes: ["128GB", "256GB", "512GB", "1TB"],
    colors: [
      "Natural Titanium",
      "Blue Titanium",
      "White Titanium",
      "Black Titanium",
    ],
    color: "Natural Titanium",
    size: "256GB",
    weight: "221g",
    height: "159.9 mm",
    company: "Apple",
    stockQuantity: 50,
    offers: ["Free AirPods with purchase", "1 Year Extended Warranty"],
    coupons: ["WELCOME10", "FIRST15"],
    faqs: [
      {
        question: "What's included in the box?",
        answer: "iPhone, USB-C to Lightning Cable, Documentation",
      },
    ],
    verified: true,
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-15T10:00:00Z",
  },
  {
    id: "2",
    name: "Samsung Galaxy S24 Ultra",
    title: "Samsung Galaxy S24 Ultra",
    description:
      "Premium Android smartphone with S Pen and advanced AI features",
    specifications: {
      Display: "6.8-inch Dynamic AMOLED 2X",
      Processor: "Snapdragon 8 Gen 3",
      Camera:
        "200MP Main, 50MP Periscope Telephoto, 10MP Telephoto, 12MP Ultra Wide",
      Storage: "256GB",
    },
    category: "electronics",
    old_price: 124999,
    our_price: 109999,
    mrp: 124999,
    discount_percentage: 12,
    discount: 12,
    images: [
      "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=500&h=500&fit=crop",
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=500&h=500&fit=crop",
    ],
    in_stock: true,
    average_rating: 4.6,
    rating: 4.6,
    review_count: 189,
    reviews: [],
    features: [
      "S Pen Included",
      "100x Space Zoom",
      "Galaxy AI",
      "Armor Aluminum Frame",
    ],
    tags: ["smartphone", "samsung", "android"],
    sizes: ["256GB", "512GB", "1TB"],
    colors: [
      "Titanium Black",
      "Titanium Gray",
      "Titanium Violet",
      "Titanium Yellow",
    ],
    color: "Titanium Black",
    size: "256GB",
    weight: "232g",
    height: "162.3 mm",
    company: "Samsung",
    stockQuantity: 35,
    offers: ["Free Galaxy Buds Pro", "Screen Protection Plan"],
    coupons: ["SAMSUNG20", "UPGRADE25"],
    faqs: [
      {
        question: "Does it support 5G?",
        answer: "Yes, it supports 5G connectivity across all major bands.",
      },
    ],
    verified: true,
    created_at: "2024-01-10T10:00:00Z",
    updated_at: "2024-01-10T10:00:00Z",
  },
  {
    id: "3",
    name: "MacBook Air M3",
    title: "MacBook Air with M3 Chip",
    description:
      "Ultra-thin laptop with M3 chip, perfect for work and creativity",
    specifications: {
      Chip: "Apple M3",
      Memory: "16GB Unified Memory",
      Storage: "512GB SSD",
      Display: "13.6-inch Liquid Retina",
    },
    category: "electronics",
    old_price: 134900,
    our_price: 124900,
    mrp: 134900,
    discount_percentage: 7,
    discount: 7,
    images: [
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=500&h=500&fit=crop",
      "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=500&h=500&fit=crop",
    ],
    in_stock: true,
    average_rating: 4.9,
    rating: 4.9,
    review_count: 156,
    reviews: [],
    features: [
      "M3 Chip",
      "All-Day Battery",
      "Fanless Design",
      "Magic Keyboard",
    ],
    tags: ["laptop", "apple", "ultrabook"],
    sizes: ["256GB", "512GB", "1TB", "2TB"],
    colors: ["Midnight", "Starlight", "Silver", "Space Gray"],
    color: "Midnight",
    size: "512GB",
    weight: "1.24 kg",
    height: "11.3 mm",
    company: "Apple",
    stockQuantity: 25,
    offers: ["Free Apple Care+ for 3 months", "Student Discount Available"],
    coupons: ["STUDENT10", "APPLE15"],
    faqs: [
      {
        question: "Battery life?",
        answer: "Up to 18 hours of battery life for typical usage.",
      },
    ],
    verified: true,
    created_at: "2024-01-08T10:00:00Z",
    updated_at: "2024-01-08T10:00:00Z",
  },
  {
    id: "4",
    name: "Women's Casual Dress",
    title: "Elegant Summer Dress",
    description: "Comfortable and stylish dress perfect for casual outings",
    specifications: {
      Material: "100% Cotton",
      Fit: "Regular",
      Sleeve: "Short Sleeve",
      Length: "Knee Length",
    },
    category: "fashion",
    old_price: 2999,
    our_price: 1999,
    mrp: 2999,
    discount_percentage: 33,
    discount: 33,
    images: [
      "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=500&h=500&fit=crop",
      "https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=500&h=500&fit=crop",
    ],
    in_stock: true,
    average_rating: 4.3,
    rating: 4.3,
    review_count: 78,
    reviews: [],
    features: [
      "Breathable Fabric",
      "Machine Washable",
      "Wrinkle Resistant",
      "Comfortable Fit",
    ],
    tags: ["dress", "women", "casual", "summer"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Blue", "Pink", "White", "Black", "Red"],
    color: "Blue",
    size: "M",
    weight: "200g",
    company: "Fashion House",
    stockQuantity: 120,
    offers: ["Buy 2 Get 1 Free", "Free Alteration"],
    coupons: ["FASHION25", "SUMMER30"],
    faqs: [
      {
        question: "Care instructions?",
        answer: "Machine wash cold, tumble dry low, iron if needed.",
      },
    ],
    verified: true,
    created_at: "2024-01-05T10:00:00Z",
    updated_at: "2024-01-05T10:00:00Z",
  },
  {
    id: "5",
    name: "The Psychology of Money",
    title: "The Psychology of Money - Morgan Housel",
    description: "Timeless lessons on wealth, greed, and happiness",
    specifications: {
      Author: "Morgan Housel",
      Pages: "256",
      Publisher: "Jaico Publishing House",
      Language: "English",
    },
    category: "books",
    old_price: 399,
    our_price: 299,
    mrp: 399,
    discount_percentage: 25,
    discount: 25,
    images: [
      "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=500&h=500&fit=crop",
      "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=500&h=500&fit=crop",
    ],
    in_stock: true,
    average_rating: 4.7,
    rating: 4.7,
    review_count: 892,
    reviews: [],
    features: [
      "Bestseller",
      "Easy to Read",
      "Practical Insights",
      "Real Examples",
    ],
    tags: ["finance", "psychology", "bestseller", "self-help"],
    company: "Jaico Publishing",
    stockQuantity: 200,
    offers: ["Free Bookmark", "Buy 3 Books Get 25% Off"],
    coupons: ["BOOKS20", "READ15"],
    faqs: [
      {
        question: "Is this suitable for beginners?",
        answer:
          "Yes, this book is written for readers of all financial backgrounds.",
      },
    ],
    verified: true,
    created_at: "2024-01-03T10:00:00Z",
    updated_at: "2024-01-03T10:00:00Z",
  },
  {
    id: "6",
    name: "Fresh Bananas",
    title: "Organic Fresh Bananas (1 Dozen)",
    description: "Fresh, ripe bananas perfect for snacking and smoothies",
    specifications: {
      Type: "Cavendish",
      Origin: "India",
      Quantity: "12 pieces",
      Organic: "Yes",
    },
    category: "groceries",
    old_price: 60,
    our_price: 48,
    mrp: 60,
    discount_percentage: 20,
    discount: 20,
    images: [
      "https://images.unsplash.com/photo-1542838132-92c53300491e?w=500&h=500&fit=crop",
      "https://images.unsplash.com/photo-1528825871115-3581a5387919?w=500&h=500&fit=crop",
    ],
    in_stock: true,
    average_rating: 4.2,
    rating: 4.2,
    review_count: 156,
    reviews: [],
    features: ["Organic", "Fresh", "Rich in Potassium", "Naturally Sweet"],
    tags: ["fruit", "organic", "healthy", "fresh"],
    company: "Fresh Farms",
    stockQuantity: 500,
    offers: ["Same Day Delivery", "Freshness Guarantee"],
    coupons: ["FRESH10", "FRUIT15"],
    faqs: [
      {
        question: "How long do they stay fresh?",
        answer: "Best consumed within 3-5 days of delivery.",
      },
    ],
    verified: true,
    created_at: "2024-01-20T10:00:00Z",
    updated_at: "2024-01-20T10:00:00Z",
  },
  {
    id: "7",
    name: "Non-Stick Frying Pan",
    title: "Premium Non-Stick Frying Pan 26cm",
    description:
      "High-quality non-stick frying pan perfect for healthy cooking",
    specifications: {
      Size: "26cm diameter",
      Material: "Aluminum with ceramic coating",
      Handle: "Heat-resistant silicone",
      Compatibility: "Induction compatible",
    },
    category: "kitchen",
    old_price: 1299,
    our_price: 899,
    mrp: 1299,
    discount_percentage: 31,
    discount: 31,
    images: [
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=500&h=500&fit=crop",
      "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=500&h=500&fit=crop",
    ],
    in_stock: true,
    average_rating: 4.4,
    rating: 4.4,
    review_count: 234,
    reviews: [],
    features: [
      "Non-Stick Coating",
      "Induction Compatible",
      "Easy to Clean",
      "Even Heat Distribution",
    ],
    tags: ["cookware", "non-stick", "kitchen", "pan"],
    colors: ["Black", "Gray"],
    color: "Black",
    company: "KitchenPro",
    stockQuantity: 75,
    offers: ["2 Year Warranty", "Free Recipe Book"],
    coupons: ["KITCHEN20", "COOK25"],
    faqs: [
      {
        question: "Is it dishwasher safe?",
        answer: "Yes, it's dishwasher safe but hand washing is recommended.",
      },
    ],
    verified: true,
    created_at: "2024-01-12T10:00:00Z",
    updated_at: "2024-01-12T10:00:00Z",
  },
  {
    id: "8",
    name: "Kids Educational Toy Set",
    title: "STEM Learning Blocks - Educational Toy Set",
    description:
      "Interactive building blocks that promote STEM learning for kids aged 3-8",
    specifications: {
      "Age Group": "3-8 years",
      Material: "Non-toxic ABS plastic",
      Pieces: "120 pieces",
      Skills: "STEM, Motor Skills, Creativity",
    },
    category: "kids",
    old_price: 1999,
    our_price: 1399,
    mrp: 1999,
    discount_percentage: 30,
    discount: 30,
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&h=500&fit=crop",
      "https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?w=500&h=500&fit=crop",
    ],
    in_stock: true,
    average_rating: 4.6,
    rating: 4.6,
    review_count: 167,
    reviews: [],
    features: [
      "Educational",
      "Safe Materials",
      "Creative Play",
      "STEM Learning",
    ],
    tags: ["toys", "educational", "STEM", "building blocks"],
    colors: ["Multicolor"],
    color: "Multicolor",
    company: "LearnToys",
    stockQuantity: 85,
    offers: ["Free Educational Guide", "Safety Certified"],
    coupons: ["KIDS20", "LEARN15"],
    faqs: [
      {
        question: "Is it safe for 3-year-olds?",
        answer: "Yes, all pieces are tested for safety and are non-toxic.",
      },
    ],
    verified: true,
    created_at: "2024-01-07T10:00:00Z",
    updated_at: "2024-01-07T10:00:00Z",
  },
];

export const mockCategories = [
  { id: "all", name: "All", count: mockProducts.length },
  {
    id: "electronics",
    name: "Electronics",
    count: mockProducts.filter((p) => p.category === "electronics").length,
  },
  {
    id: "fashion",
    name: "Fashion",
    count: mockProducts.filter((p) => p.category === "fashion").length,
  },
  {
    id: "books",
    name: "Books",
    count: mockProducts.filter((p) => p.category === "books").length,
  },
  {
    id: "groceries",
    name: "Groceries",
    count: mockProducts.filter((p) => p.category === "groceries").length,
  },
  {
    id: "kitchen",
    name: "Kitchen",
    count: mockProducts.filter((p) => p.category === "kitchen").length,
  },
  {
    id: "kids",
    name: "Kids",
    count: mockProducts.filter((p) => p.category === "kids").length,
  },
];
