/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    screens: {
      xs: { max: "378px" },
      suf: { min: "556px", max: "767px" },
      sm_md: { min: "376px", max: "767px" },
      // md: "772px",
      // lg:"925px",
    sxxs: "255px",
    sxs: "265px",
    sxs1: "275px",
    sxs2: "285px",
    sxs3: "295px",
    ss: "305px",
    ss1: "315px",
    ss2: "325px",
    ss3: "335px",
    ss4: "345px",
    dxs: "375px",
    xxs: "405px",
    xxs1: "425px",
    sm0: "445px",
    sm1: "480px",
    sm4: "508px",
    sm2: "538px",
    sm3: "550px",
    sm5: "600px",
    sm: "640px",
    md: "768px",
    md1: "870px",
    md2: "914px",
    md3: "936px",
    lg: "976px",
    dlg: "1024px",
    dlg1: "1060px",
    dlg2: "1090px",
    lg1: "1100px",
    lg2: "1123px",
    lgx: "1134px",
    lgx1: "1159px",
    lgx2: "1193px",
    dxl0: "1240px",
    dxl: "1280px",
    dxl1: "1380px",
    xl: "1440px",
    xl2: "1600px",
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [],
}